/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RewardsTask {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'description' : string,
  'points' : bigint,
}
export type TaskStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface TaskSubmission {
  'status' : TaskStatus,
  'taskId' : bigint,
  'timestamp' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : WithdrawalStatus,
  'timestamp' : number,
  'amount' : bigint,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTask' : ActorMethod<[string, string, bigint, string], undefined>,
  'createWithdrawalRequest' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<RewardsTask>>,
  'getAllTasksByTitle' : ActorMethod<[], Array<RewardsTask>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPointsBalance' : ActorMethod<[], bigint>,
  'getTaskSubmissions' : ActorMethod<[], Array<TaskSubmission>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reviewWithdrawalRequest' : ActorMethod<
    [Principal, bigint, boolean],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitTask' : ActorMethod<[bigint], undefined>,
  'verifyTaskSubmission' : ActorMethod<[Principal, bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];